stages:
  - release

release:
  stage: release
  image: eclipse-temurin:17-jdk
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_PIPELINE_SOURCE == "web"
  before_script:
    - mkdir -p ~/.gradle
    - echo "gpr.user=${GPR_USER}" >> ~/.gradle/gradle.properties
    - echo "gpr.key=${GPR_KEY}" >> ~/.gradle/gradle.properties
    - apt-get update && apt-get install -y nodejs npm git jq
  script:
    - ./gradlew :patches:buildAndroid :patches:generatePatchesList
    - npm install
    - npx semantic-release
  artifacts:
    paths:
      - patches/build/libs/*.mpp
